pipeline{

    agent none

    stages{
        stage('Build JAR'){
            agent {
               docker {
                   image 'maven:3.9.3-eclipse-temurin-17-focal'
                   args '-u root -v /tmp/.m2:/root/.m2'
               }
            }
            steps{
                sh 'mvn -pl overAll clean package -DskipTests'
            }
        }
        stage('Build Docker Image'){
            steps{
                script{
                        app = docker.build('radulenko/selenium:latest', './overAll')
                }
            }
        }


        stage('Push Docker Image'){
             steps{
                script{
                   docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-cred'){
                       app.push('latest')
                       app.push("NEW_V_${env.BUILD_NUMBER}")
                    }

                }
             }
        }

    }


}